#!/bin/sh -e

if [ -z "`grep -e '^gnokii:' /etc/group`" ]
then
	/usr/sbin/groupadd gnokii
else
	echo 'notice: group "gnokii" already exists'
	echo 'I assume that you have used a gnokii before, Mr. Bond.'
fi

#DEBHELPER#
