#!/usr/bin/env python

import pynotify
import sys

# Mandatory arguments are phone number and SMS date
if len(sys.argv) <> 3:
    exit(-1)

phone_number = sys.argv[1]
sms_date = sys.argv[2]
sms_body = sys.stdin.read()

note_title = "SMS from %s" % phone_number

if __name__ == '__main__':
    if not pynotify.init("SMS"):
        sys.exit(1)

    n = pynotify.Notification(note_title,
                              "Date: " + sms_date + "\n\n" + sms_body)
    # show this in the default position, we can't set coordinates since with haven't got an icon
    #n.set_hint("x", 0)
    #n.set_hint("y", 0)

    if not n.show():
        print "Failed to send notification"
        sys.exit(1)

