#!/usr/bin/env python
import sys, dbus

# Mandatory arguments are phone number and SMS date
if len(sys.argv) <> 3:
    exit(-1)

phone_number = sys.argv[1]
sms_date = sys.argv[2]
sms_body = sys.stdin.read()

note_title = "SMS from %s" % phone_number

bus = dbus.SessionBus()
obj = bus.get_object("org.gnome.Tomboy", "/org/gnome/Tomboy/RemoteControl")
tomboy = dbus.Interface(obj, "org.gnome.Tomboy.RemoteControl")

# Add to existing note or create a new one
note = tomboy.FindNote(note_title)
if note == "":
    note = tomboy.CreateNamedNote(note_title)
    tomboy.SetNoteContents(note, note_title)

# NOTE: due to a bug, Tomboy can set links properly only if note is open
tomboy.DisplayNote(note)
tomboy.SetNoteContents(note, tomboy.GetNoteContents(note) + "\n\n" + sms_date + "\n\n" + sms_body)
tomboy.AddTagToNote(note, "SMS")
tomboy.AddTagToNote(note, "Inbox")
